[SupersonicTheme]
Name = "Catppuccin Latte (Pink)"
Version = "0.2"
SupportsDark = false
SupportsLight = true

[LightColors]
PageBackground = "#EFF1F5FF"
ListHeader = "#DCE0E8FF"
PageHeader = "#E6E9EFFF"
Background = "#DCE0E8FF"
Button = "#BCC0CCFF"
DisabledButton = "#E6E9EFFF"
Disabled = "#BCC0CCFF"
Error = "#D20F39FF"
Focus = "#9CA0B0FF"
Foreground = "#4C4F69FF"
Hover = "#9CA0B0FF"
Hyperlink = "#EA76CBFF"
InputBackground = "#BCC0CCFF"
InputBorder = "#7287FDFF"
MenuBackground = "#CCD0DAFF"
OverlayBackground = "#ACB0BEFF"
Pressed = "#EA76CBFF"
Primary = "#EA76CBFF"
ScrollBar = "#8C8FA1FF"
Selection = "#E6E9EFFF"
Separator = "#BCC0CCFF"
Success = "#40A02BFF"
Warning = "#FE640BFF"
