[SupersonicTheme]
Name = "Catppuccin Frappé (Peach)"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#303446FF"
ListHeader = "#232634FF"
PageHeader = "#292C3CFF"
Background = "#232634FF"
Button = "#51576DFF"
DisabledButton = "#292C3CFF"
Disabled = "#51576DFF"
Error = "#E78284FF"
Focus = "#737994FF"
Foreground = "#C6D0F5FF"
Hover = "#737994FF"
Hyperlink = "#EF9F76FF"
InputBackground = "#51576DFF"
InputBorder = "#BABBF1FF"
MenuBackground = "#414559FF"
OverlayBackground = "#626880FF"
Pressed = "#EF9F76FF"
Primary = "#EF9F76FF"
ScrollBar = "#838BA7FF"
Selection = "#292C3CFF"
Separator = "#51576DFF"
Success = "#A6D189FF"
Warning = "#EF9F76FF"
